language: python
dist: xenial # trusty doesn't support Py3.7

cache:
    apt: true
    pip: true
    ccache: true

matrix:
    include:
        - &python36
          python: '3.6'
        - &python37
          python: '3.7'

before_install:
    - pip install -U setuptools pip wheel
    - pip install codecov

install:
    - pip install pyqt5==5.11.*
    - travis_wait pip install -e .

script:
    - XVFBARGS="-screen 0 1280x1024x24"
    - catchsegv xvfb-run -a -s "$XVFBARGS" coverage run setup.py test

after_success:
    - codecov
